codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

flags:
  unittests:
    paths:
      - apps/admin-dashboard/src/
    carryforward: true
  integration:
    paths:
      - apps/admin-dashboard/src/app/api/
    carryforward: true
  e2e:
    paths:
      - apps/admin-dashboard/e2e/
    carryforward: true

ignore:
  - "**/*.d.ts"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "apps/admin-dashboard/src/components/ui/**"  # Shadcn UI components
  - "apps/admin-dashboard/src/lib/supabase/database.types.ts"  # Generated types
