#!/bin/bash
# ZERO-TOUCH MIGRATION EXECUTOR
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT EDIT - AUTO-GENERATED BY SRE SYSTEM

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Config
MIGRATION_FILE="supabase/migrations/006_schema_audit_remediation.sql"
PROJECT_REF="elruhdwcrsxeirbbsozd"
BACKUP_MARKER="pre_migration_$(date +%s)"

echo -e "${GREEN}🚀 ZERO-TOUCH MIGRATION STARTING${NC}"
echo "================================================"
echo "Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "Project: $PROJECT_REF"
echo "Migration: $MIGRATION_FILE"
echo "================================================"
echo ""

# Check if running in Supabase environment
if command -v supabase &> /dev/null && supabase projects list 2>/dev/null | grep -q "$PROJECT_REF"; then
    echo -e "${GREEN}✅ Supabase CLI authenticated${NC}"
    
    # Method 1: Direct Supabase CLI push
    echo "📤 Executing via Supabase CLI..."
    supabase db push --include-all
    
else
    echo -e "${YELLOW}⚠️  Supabase CLI not authenticated${NC}"
    echo ""
    echo "Execute ONE of the following methods:"
    echo ""
    
    # Method 2: SQL Editor
    echo -e "${GREEN}METHOD 1: Supabase Dashboard (Recommended)${NC}"
    echo "1. Go to: https://supabase.com/dashboard/project/$PROJECT_REF/sql/new"
    echo "2. Copy content from: $MIGRATION_FILE"
    echo "3. Click 'Run'"
    echo ""
    
    # Method 3: psql
    echo -e "${GREEN}METHOD 2: psql CLI${NC}"
    echo "Run:"
    echo "  psql \"postgresql://postgres:PASSWORD@db.$PROJECT_REF.supabase.co:5432/postgres\" \\"
    echo "    -v ON_ERROR_STOP=1 \\"
    echo "    -f $MIGRATION_FILE"
    echo ""
    
    # Auto-open browser (macOS)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "🌐 Opening Supabase Dashboard..."
        open "https://supabase.com/dashboard/project/$PROJECT_REF/sql/new"
    fi
fi

echo ""
echo -e "${GREEN}================================================${NC}"
echo "Migration execution initiated"
echo "Monitor at: https://supabase.com/dashboard/project/$PROJECT_REF"
echo -e "${GREEN}================================================${NC}"
